### ISSUE TITLE
I2C use?

### ISSUE THREAD

**Issue by nihilisticeevee** [unprovable/FTDI-Oh-My#2]
Has anyone figured out how to use the I2C on this?

**Comment by unprovable** [comment]
Hello,

Not that I have seen in python, but the manufacturer published the following note: http://www.ftdichip.com/Support/Documents/AppNotes/AN_255_USB%20to%20I2C%20Example%20using%20the%20FT232H%20and%20FT201X%20devices.pdf

Is that enough for you to use? If I can help, let me know. I've not had to use these for I2C yet, but happy to test locally.

Cheers, M.

**Comment by nihilisticeevee** [comment]
This looks to be very helpful, thank you very much! From what i read AD0 is SCL and AD1 and AD2 connected together are SDA. Electronics is very to to me so hopefully i figure it out. Thanks again!
